AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Removes one favorited set from the user metadata Favorited Set Documents list.
Resources:
  DeleteFavoritedSetFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/delete_user_favorite_set-1.0.jar
      Handler: com.revature.delete_user_favorites.DeleteUserFavoritesHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::011217676466:policy/dynamodb-update-users-item
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess